#MongoDB Database Configuration
spring.application.name=TaskPrompter-MongoDB
spring.data.mongodb.uri= YOUR DATABASE CONNECTION URL
spring.data.mongodb.database=TaskPrompter

#SMTP Mail Configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= YOUR MAIL
spring.mail.password= YOUR PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG

#Google Oauth Signin Configurations
spring.security.oauth2.client.registration.google.client-id= YOUR OAUTH CLIENT-ID
spring.security.oauth2.client.registration.google.client-secret= YOUR OAUTH SECRET-KEY
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


